<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Selenium.Support" Version="4.45.0" />
    <PackageReference Include="Selenium.WebDriver.ChromeDriver" Version="150.0.7871.4600" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NzbDrone.Test.Common\Sonarr.Test.Common.csproj" />
  </ItemGroup>
</Project>
